tls_context:
  common_tls_context:
    tls_params:
      tls_minimum_protocol_version: TLSv1_3
      cipher_suites: ECDHE-ECDSA-AES256-GCM-SHA384
    supported_groups: X25519MLKEM768:X25519:secp384r1
